### ISSUE TITLE
Looking for a champion

### ISSUE THREAD

**Issue by gyzerok** [gyzerok/ecmascript-arrow-function-declaration#3]
Currently I'm looking for a champion to be able to propose this syntax.

**Comment by gyzerok** [comment]
@sebmarkbage can you be the one?

**Comment by sebmarkbage** [comment]
Unfortunately my time is limited and I don't think I'm passionate enough to champion this. However, maybe if you sold me on it.

Why don't you just use a function declaration? It doesn't seem like you need to bind this or anything.

**Comment by gyzerok** [comment]
@sebmarkbage the primary pain here is not `this` binding but a lot of boilerplate with function declaration usage.

``` js
function map(predicate) {
  return function (list) {
    // Implementation
  }
}

// ES5
function squares(list) {
  return map(x => x * x)(list);
}

// ES6
const squares = map(x => x * x)
```

When you are using javascript in a functional way ES6 approach feels extremly better however it lacks hoisting. So currently you have to define functions in the strict order if you are using ES6 approach. Here proposed syntax provides symmetry between function declarations and expressions in ES5 and ES6 ones. Mostly because of symmetry I'm talking about `this` binding, but we can dismiss it and use:

``` js
// with binding approach
function fname(fargs) => fbody
// without binding approach
function fname(fargs) = fbody
```

A lot of engineers tries to get rid of `this` in javascript now since `this` adds implicitness. I guess proposed syntax would help to move in that. I appreciate your thoughts about minimal API surface area and I do not think my proposal adds real noise to js. But later on ECMAScript could forget about common (not arrow) functions completely if it would be the goal, and we would be able to remove some syntax to reduce API area.

Maybe if you cannot champion my proposal you can recommend someone? I'd try to contact with one and discuss this.

**Comment by natew** [comment]
Why not add a new declarator. It works exactly like const, except it hoists your variable. `def`.

```js
def fname = x => x.map(y => y.title
def fname = x => x.map(y => y.title
def fname = x => x.map(y => y.title


```

**Comment by natew** [comment]
Why not add a new declarator. It works exactly like const, except it hoists your variable. One, it lets you avoid making a new way of defining functions.

Two, `const` is probably the most annoying declarator I've seen, def would fit with `let`.

``` js
def fname = x => x.map(y => y.title)
```

While I'm making crazy suggestions, lets make  `def` somehow be shorthand for a function that defines a variable to the value it receives (this syntax is bad, but somehow), I would be so happy:

``` js
let x = 0
fetch().then(title => def x)

// because this pattern is way too common
let x = 0
const set = _x => x = _x
```

**Comment by gyzerok** [comment]
@natew There is no reserved word for this. So it would be a breaking change.
